import Head from 'next/head'
import { Inter } from 'next/font/google'
import { getAuth, signInWithPopup, GoogleAuthProvider } 
from "firebase/auth";
import { initFirebase } from '@/firebase/firebase';
import {useAuthState} from "react-firebase-hooks/auth"
import { useRouter } from 'next/router';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import * as React from 'react';
import CardMedia from '@mui/material/CardMedia';
import { CardActionArea} from '@mui/material';

const inter = Inter({ subsets: ['latin'] })

export default function Home():any {
 
initFirebase();
const provider = new GoogleAuthProvider();
const auth= getAuth();
 const [user,loading]=useAuthState(auth);
 const router = useRouter();


if(loading){
  return <div>Loading...</div>
}
if(user){
 router.push("/dashboard")
   return <div> bienvenido {user.displayName}</div>

}

   const signIn = async ()=>{
     const result = await signInWithPopup(auth,provider);
     console.log(result.user)
   }

   const bull = (
    <Box
    component="span"
    sx={{ display: 'inline-block', mx: '2px', transform: 
      'scale(0.8)' }}>
      • </Box>
      );
    



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
<main>

<Box
  display="flex"
  justifyContent="center"
  alignItems="center"
  minHeight="100vh"
>

<Card sx={{ maxWidth: 345 }}>
      <CardActionArea>
        <CardMedia
          component="img"
          height="140"
          image="https://raw.githubusercontent.com/victorzam7565/tienda.online-next.js.-/main/public/img/octocat.webp"
          alt="green iguana"
        />
        <CardContent>
          <Typography gutterBottom variant="h5" component="div">
            verifica con tu Mail para entrar
          </Typography>
          <Typography variant="body2" color="text.secondary">
 esta listo este pequeño ejercicio con material-ui typescript next.js y base de datos firebase <nav></nav>
          </Typography>
        </CardContent>
      </CardActionArea>
      <CardActions>
        <Button variant="contained" size="small" color="warning" onClick={signIn} >
          verifica aqui con tu correo 
        </Button>
      </CardActions>
    </Card>

    </Box>
</main>
    </>
    
  )
}
